NAME = ft_display_file
FLAGS = -Wall -Werror -Wextra
SRC = ./ft_display_file.c
all: $(NAME)
$(NAME):
	cc $(FLAGS) $(SRC) -o $(NAME)
clean:
	rm -f ft_display_ft.o
fclean: clean
	rm -f $(NAME)
.PHONY: fclean clean all
